import AuthNavbar from "@/components/Navbar/AuthNavbar"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}
  
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body>
            <div className="shadow-sm dark:shadow-blue-500/20 sticky top-0 backdrop-blur-lg">
                <AuthNavbar />
            </div>
            {children}
        </body>
        </html>
    )
}